# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 15s  # scrape_timeout is set to 15s to comply with older/stacked devices.

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# scrape configuration:
scrape_configs:
  - job_name: snmp
    static_configs:
      - targets:
          - 10.10.1.254
          - 10.10.1.1
          - 10.10.1.2
          - 10.10.1.3
    metrics_path: /snmp
    params:
      auth:
        - public_v2
      module:
        - zyxel_device
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: 10.10.1.247:9116
  - job_name: snmp_exporter
    static_configs:
      - targets:
          - 10.10.1.247:9116

